import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {

    width: 200px;
    height: 200px;
    Rectangle {

        width: parent.width;
        height: parent.width;
        background: blue;

    }
    in-out property<int> counter: 42;
    callback request-increase-value();
    VerticalBox {
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
